### PR TITLE
Added Nix development shell and packaging

### PR DESCRIPTION
**Pull request by arichtman**
Hey, thanks for this handy tool!

I know nobody asked but I added some Nix packaging and development environment.

Feel free to reject this or modify it how you like =]

### CODE REVIEW

**Comment by magodo** [comment]
@arichtman Sorry, I'm not familiar with the packaging under Nix, looking at some existing toolings that have Nix support (e.g. https://github.com/BurntSushi/ripgrep), looks like there is no `.nix` files at all. So I assume those files should reside in else where?

**Comment by arichtman** [comment]
For packages to show on nixos.org packaging list they get added to github/nixos/nixpkgs.
Repgrep can be found here https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/text/ripgrep/default.nix

**I suppose we could see about adding it to nixpkgs but I wasn't sure if you were OK with that or if anyone else would be interested?**

If we add the package to this repository then users can build/run it directly from here, without having to set up anything

image

**Comment by magodo** [comment]
@arichtman Could those files be reside in a dedicated folder? Otherwise, the root folder looks a bit messy.

**Comment by arichtman** [comment]
Ok I moved the ones I could, I think flake.nix has to stay in root as the entry point :S

**Comment by magodo** [comment]
@arichtman Do you mind kindly provide me some example repos that have this setup?

**Pull request closed without merging**
